@extends('layouts.public')

@section('content')
<div class="row">
    <div class="col-lg-8">
        @if(config('app.locale') == 'es')
            <h3>TÉRMINOS Y CONDICIONES DE USO DEL SITIO WEB</h3>
            <p>Este es el sitio Web oficial que el Ayuntamiento de Altea pone a disposición de los/as ciudadanos/as de Altea y de todos los/las usuarios/as de la red Internet. Su objetivo es suministrar servicio e información a dichos usuarios/as y proyectar y dar a conocer así la ciudad de Altea y su actividad. Un portal de información virtual que aspira a convertirse en un punto de referencia y encuentro entre los vecinos de Altea, para acercar a todos los ciudadanos los diferentes servicios y recursos municipales, además de facilitar de manera cómoda y sencilla los trámites y las gestiones con esta institución.</p>
            <p>Todos los derechos están reservados. No está permitida la modificación de la Web ni de sus contenidos. Todos ellos son propiedad de Ayuntamiento de Altea, si no se indica lo contrario. Pueden ser reproducidos libremente y para fines no lucrativos por cualquier persona perteneciente a una institución de carácter educativo o investigador, siempre y cuando se cite la fuente de la información. Otras instituciones, organismos, empresas, etc deben solicitar el permiso escrito de los propietarios del copyright.</p>
            <p>La información administrativa facilitada a través de este Web no sustituye la publicidad de los documentos que deban publicarse en Diarios y Boletines Oficiales, cuya edición es instrumento que da fe de su contenido.</p>
            <p>El Ayuntamiento de Altea no es responsable del contenido, exactitud y actualización de la información que proviene de otras personas físicas o jurídicas y que conste en el sitio Web o a la que se remita a partir de enlaces u otros sistemas. En este sitio Web oficial el usuario podrá encontrar diversos enlaces que le conducirán a páginas Web independientes de ésta. Su única finalidad es la de facilitar el acceso a otras fuentes de información en Internet relacionadas con la actividad de la ciudad y su inserción en este sitio Web está inspirada en el respeto de los derechos de propiedad intelectual que, en su caso, puedan corresponder a sus autores. Asimismo, el establecimiento de enlaces al sitio Web del Ayuntamiento de Altea deberá respetar los derechos de propiedad intelectual de titularidad municipal.</p>
            <p>El Ayuntamiento de Altea no se hace responsable del uso por terceros de la información contenida, si bien éstos tendrán que atenerse a las advertencias que consten para determinados documentos y aplicativos.</p>
            <p>Todos los datos suministrados por los/las usuarios/as no se destinarán a otras finalidades que las expresadas en cada caso, ni tampoco se facilitarán a terceros, de acuerdo con los principios de protección de datos de carácter personal que establece la Ley Orgánica de Protección de Datos (Ley 15/1999, de 13 de diciembre).</p>
            <p>El Ayuntamiento de Altea utiiliza todos los medios disponibles para que los contenidos del sitio Web estén libres de virus informáticos. No obstante, no acepta ninguna responsabilidad por los posibles daños causados por los mismos, cuya ausencia no queda garantizada.</p>
            <p>El Ayuntamiento de Altea se reserva el derecho a modificar y ampliar contenidos, informaciones, aplicativos, etc. de este sitio Web en cualquier momento y sin previo aviso.</p>
            <p>El interés del Ayuntamiento de Altea es el de que este sitio Web funcione con la máxima eficacia y cumpla la finalidad para la que ha sido creado. Por ello lo mantiene, poniendo todos los medios razonables para conseguirlo, pero no se responsabiliza de posibles disfunciones y/o anomalías en su funcionamiento causadas por una circunstancia accidental, fuerza mayor o trabajos de mantenimiento, que imposibiliten el correcto acceso al sitio Web.</p>
            <p>El Ayuntamiento de Altea podrá modificar los términos y condiciones que aparecen en esta página Web y, por tanto, aconseja su consulta con una periodicidad razonable por si se producen cambios en los mismos.</p>
            <p>El uso de este sitio Web implica el conocimiento y la aceptación de los términos y condiciones contenidos en el mismo. Además la utilización de determinados servicios a disposición de los usuarios de este sitio oficial puede estar sometida a condiciones especiales, advertencias o instrucciones que también deberán ser consultadas y aceptadas sin reservas por los usuarios.</p>
            <p>Para cualquier aclaración, información, sugerencia, queja, etc. pueden utilizar el buzón de sugerencias de esta Web o dirigirse a la Concejalía de Comunicación, Plaza de José María Planelles, 03590 Altea (Alicante).</p>
            <p>Los/las usuarios/as pueden ejercer su derecho de acceso, rectificación, cancelación y oposición que les otorga la vigente Ley Orgánica de Protección de Datos (Ley 15/1999, de 13 de diciembre) sobre sus datos, solicitándolo con previa identificación, personalmente, por teléfono, por correo, fax o correo electrónico.</p>
        @else
            <h3>TERMES I CONDICIONS D’ÚS DEL LLOC WEB</h3>
            <p>Aquest és el lloc web oficial que l’Ajuntament d’Altea posa a la disposició dels/as ciutadans/as d’Altea i de tots els/les usuaris/as de la xarxa Internet. El seu objectiu és subministrar servei i informació a dites usuàries/as i projectar i donar a conèixer així la ciutat d’Altea i la seua activitat. Un portal d’informació virtual que aspira a convertir-se en un punt de referència i trobada entre els veïns d’Altea, per a acostar a tots els ciutadans els diferents serveis i recursos municipals, a més de facilitar de manera còmoda i senzilla els tràmits i les gestions amb aquesta institució.</p>
            <p>Tots els drets estan reservats. No està permesa la modificació de la Web ni dels seus continguts. Tots ells són propietat d’Ajuntament d’Altea, si no s’indica el contrari. Poden ser reproduïts lliurement i per a finalitats no lucratives per qualsevol persona pertanyent a una institució de caràcter educatiu o investigador, sempre que se cite la font de la informació. Altres institucions, organismes, empreses, etc han de sol·licitar el permís escrit dels propietaris del copyright.</p>
            <p>La informació administrativa facilitada a través d’aquest Web no substitueix la publicitat dels documents que hagen de publicar-se en Diaris i Butlletins Oficials, l’edició dels quals és instrument que dóna fe del seu contingut.</p>
            <p>L’Ajuntament d’Altea no és responsable del contingut, exactitud i actualització de la informació que prové d’altres persones físiques o jurídiques i que conste en el lloc web o a la qual es remeta a partir d’enllaços o altres sistemes. En aquest lloc web oficial l’usuari podrà trobar diversos enllaços que li conduiran a pàgines Web independents d’aquesta. La seua única finalitat és la de facilitar l’accés a altres fonts d’informació en Internet relacionades amb l’activitat de la ciutat i la seua inserció en aquest lloc web està inspirada en el respecte dels drets de propietat intel·lectual que, si escau, puguen correspondre als seus autors. Així mateix, l’establiment d’enllaços al lloc web de l’Ajuntament d’Altea haurà de respectar els drets de propietat intel·lectual de titularitat municipal.</p>
            <p>L’Ajuntament d’Altea no es fa responsable de l’ús per tercers de la informació continguda, si ben aquests hauran d’atenir-se als advertiments que consten para determinats documents i aplicatius.</p>
            <p>Totes les dades subministrades per els/les usuaris/as no es destinaran a altres finalitats que les expressades en cada cas, ni tampoc es facilitaran a tercers, d’acord amb els principis de protecció de dades de caràcter personal que estableix la Llei Orgànica de Protecció de Dades (Llei 15/1999, de 13 de desembre).</p>
            <p>L’Ajuntament d’Altea utiiliza tots els mitjans disponibles perquè els continguts del lloc web estiguen lliures de virus informàtics. No obstant açò, no accepta cap responsabilitat pels possibles danys causats pels mateixos, l’absència dels quals no queda garantida.</p>
            <p>L’Ajuntament d’Altea es reserva el dret a modificar i ampliar continguts, informacions, aplicatius, etc. d’aquest lloc web en qualsevol moment i sense previ avís.</p>
            <p>L’interès de l’Ajuntament d’Altea és el que aquest lloc web funcione amb la màxima eficàcia i complisca la finalitat per a la qual ha sigut creat. Per açò ho manté, posant tots els mitjans raonables per a aconseguir-ho, però no es responsabilitza de possibles disfuncions i/o anomalies en el seu funcionament causades per una circumstància accidental, força major o treballs de manteniment, que impossibiliten el correcte accés al lloc web.</p>
            <p>L’Ajuntament d’Altea podrà modificar els termes i condicions que apareixen en aquesta pàgina Web i, per tant, aconsella la seua consulta amb una periodicitat raonable per si es produeixen canvis en els mateixos.</p>
            <p>L’ús d’aquest lloc web implica el coneixement i l’acceptació dels termes i condicions continguts en el mateix. A més la utilització de determinats serveis a la disposició dels usuaris d’aquest lloc oficial pot estar sotmesa a condicions especials, advertiments o instruccions que també hauran de ser consultades i acceptades sense reserves pels usuaris.</p>
            <p>Per a qualsevol aclariment, informació, suggeriment, queixa, etc. poden utilitzar la bústia de suggeriments d’aquesta Web o dirigir-se a la Regidoria de Comunicació, Plaza de José María Planelles, 03590 Altea (Alacant).</p>
            <p>Els/les usuaris/as poden exercir el seu dret d’accés, rectificació, cancel·lació i oposició que els atorga la vigent Llei Orgànica de Protecció de Dades (Llei 15/1999, de 13 de desembre) sobre les seues dades, sol·licitant-ho amb prèvia identificació, personalment, per telèfon, per correu, fax o correu electrònic.</p>
        @endif
    </div>
</div>
@endsection
